#!/bin/sh
 
# Exit on error
set -e

lib="/usr/lib"

if [ -f ${lib}/libcxgb4_sock.so ]; then
    unlink ${lib}/libcxgb4_sock.so;
fi
if [ -f ${lib}/libcxgb4_sock.so.1 ]; then
    unlink ${lib}/libcxgb4_sock.so.1
fi

exit 0
