#!/bin/sh
 
# Exit on error
set -e

lib="/usr/lib"

if [ -f  ${lib}/libwdtoe_debug.so ]; then
    unlink ${lib}/libwdtoe_debug.so;
fi
if [ -f ${lib}/libwdtoe_debug.so.1 ]; then
    unlink ${lib}/libwdtoe_debug.so.1;
fi

exit 0
